plugins {
    id 'java'
    id 'eclipse'
    id 'idea'
    id 'org.sonarqube' version '6.0.0.5145'
    id 'net.serenity-bdd.serenity-gradle-plugin' version '4.2.8'
    id 'com.diffplug.spotless' version '6.25.0'
    id 'org.gradle.test-retry' version '1.6.0'
}

repositories {
    mavenLocal()
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

ext {
    versions = [
            serenityCore : '4.2.9',
            cucumber     : '7.20.1',
            junit        : '5.11.3',
            junitPlatform: '1.11.3',
            aeonbits     : '1.0.12',
            gson         : '2.10.1',
            slf4j        : '2.0.13',
            appium       : '9.3.0',
            googleFormat : '1.25.2'
    ]
}

dependencies {
    implementation "org.aeonbits.owner:owner:${versions.aeonbits}",
            "org.slf4j:slf4j-simple:${versions.slf4j}"
    testImplementation "org.slf4j:slf4j-api:${versions.slf4j}",
            "com.google.code.gson:gson:${versions.gson}",
            "net.serenity-bdd:serenity-core:${versions.serenityCore}",
            "net.serenity-bdd:serenity-ensure:${versions.serenityCore}",
            "net.serenity-bdd:serenity-screenplay:${versions.serenityCore}",
            "net.serenity-bdd:serenity-screenplay-webdriver:${versions.serenityCore}",
            "net.serenity-bdd:serenity-cucumber:${versions.serenityCore}",
            "org.junit.jupiter:junit-jupiter-api:${versions.junit}",
            "org.junit.platform:junit-platform-suite:${versions.junitPlatform}",
            "io.cucumber:cucumber-java:${versions.cucumber}",
            "io.cucumber:cucumber-junit-platform-engine:${versions.cucumber}",
            "io.appium:java-client:${versions.appium}"

    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:${versions.junit}"
}

spotless {
    encoding 'UTF-8'
    // Set the encoding, replace 'UTF-8' with `${encoding}` if it's dynamically defined

    java {

        // Exclude specific folder
        targetExclude('/target/**/*', 'build/**/*', 'node_modules/**/*')

        // Apply Google Java Format with a specific style and options
        googleJavaFormat("${versions.googleFormat}").aosp().reflowLongStrings(true)

        // License header configuration
        licenseHeaderFile 'LICENSE', 'package '
    }

    groovyGradle {
        target '*.gradle', 'gradle/*.gradle'
    }

    format 'dotfiles', {
        target '.gitignore', '.gitattributes', '.editorconfig'
        indentWithSpaces(2)
        trimTrailingWhitespace()
        endWithNewline()
    }

    // Format SQL files
    sql {
        target '**/*.sql' // Define which files to include
        targetExclude('/target/**/*', 'build/**/*', 'node_modules/**/*')
        // Exclude specific folder
        dbeaver()         // Apply DBeaver formatting conventions
    }

    // Format JSON files
    json {
        target '**/*.json'
        targetExclude('/target/**/*', 'build/**/*', 'node_modules/**/*')
        // Exclude specific folder
        gson() // Apply Gson-based formatting
    }
}

test {
    onlyIf { // Run Only When Explicitly Invoked
        gradle.startParameter.taskNames.contains('test')
    }
    useJUnitPlatform()
    testLogging {
        //showStandardStreams = true
        events "PASSED", "FAILED", "SKIPPED"
    }
    systemProperties System.getProperties()
    systemProperty 'serenity.generateOutcomes', 'false' // Disable reports during tests
    retry {
        maxRetries = 0 // Disables test retries
    }
}

serenity {
    outputDirectory = file("build/site/serenity")
    generateOutcomes = true // Disable automatic report generation globally
}

tasks.withType(Test).configureEach {
    //maxParallelForks = Runtime.runtime.availableProcessors().intdiv(2) ?: 1
    maxParallelForks = Runtime.runtime.availableProcessors()
    forkEvery = 1 // This can help with managing test isolation
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.incremental = true
}

tasks.withType(Javadoc).configureEach {
    options.encoding = 'UTF-8'
}

// Tasks for checking and applying formats
tasks.named('spotlessApply') {
    group = 'formatting'
}

tasks.named('spotlessCheck') {
    group = 'verification'
}

sonar {
    properties {
        property "sonar.coverage.exclusions", "src/**/*.java"
        property "sonar.sources", "src"
        property "sonar.test.exclusions", "src/test/**/*.java"
        property "sonar.host.url", "http://127.0.0.1:9000"
        property "sonar.java.binaries", "build/classes"
        property "sonar.scm.provider", "git"
    }
}

tasks.register('npmInstall', Exec) {
    commandLine 'npm', 'install'
}

tasks.register('installLocalGitHook', Copy) {
    from new File(rootProject.rootDir, 'scripts/pre-commit')
    into { new File(rootProject.rootDir, '.git/hooks') }
    fileMode 0775
}

tasks.named('build') {
    dependsOn npmInstall, installLocalGitHook
}

tasks.named('sonar') {
    dependsOn spotlessApply, build
}

tasks.named('aggregate') {
    onlyIf { // Run Only When Explicitly Invoked
        gradle.startParameter.taskNames.contains('aggregate')
    }
}

// gradle.startParameter.continueOnFailure = true
gradle.startParameter.continueOnFailure = false
