import java.text.SimpleDateFormat

plugins {
    id 'java'
    id 'eclipse'
    id 'idea'
    id 'org.sonarqube' version '6.0.0.5145'
    id 'net.serenity-bdd.serenity-gradle-plugin' version '4.2.16'
    id 'com.diffplug.spotless' version '6.25.0'
    id 'org.gradle.test-retry' version '1.6.0'
    id 'org.caffinitas.gradle.testsummary' version '0.1.1'
}

repositories {
    mavenLocal()
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
    toolchain.languageVersion.set(JavaLanguageVersion.of(21))
}

ext {
    versions = [
            serenityCore : '4.2.17',
            cucumber     : '7.21.1',
            junit        : '5.12.1',
            junitPlatform: '1.12.1',
            archUnit     : '1.4.0',
            aeonbits     : '1.0.12',
            gson         : '2.12.1',
            slf4j        : '2.0.17',
            appium       : '9.4.0',
            googleFormat : '1.25.2',
            lombok       : '1.18.36'
    ]
}

dependencies {
    implementation "org.aeonbits.owner:owner:${versions.aeonbits}",
            "org.slf4j:slf4j-simple:${versions.slf4j}",
            "org.slf4j:slf4j-api:${versions.slf4j}",
            "com.google.code.gson:gson:${versions.gson}",
            "net.serenity-bdd:serenity-core:${versions.serenityCore}",
            "net.serenity-bdd:serenity-junit5:${versions.serenityCore}",
            "net.serenity-bdd:serenity-ensure:${versions.serenityCore}",
            "net.serenity-bdd:serenity-screenplay:${versions.serenityCore}",
            "net.serenity-bdd:serenity-screenplay-webdriver:${versions.serenityCore}",
            "net.serenity-bdd:serenity-cucumber:${versions.serenityCore}",
            "io.appium:java-client:${versions.appium}"

    testImplementation "io.cucumber:cucumber-java:${versions.cucumber}",
            "io.cucumber:cucumber-junit-platform-engine:${versions.cucumber}",
            "junit:junit:4.13.2", // Required for compatibility with cucumber
            "org.junit.platform:junit-platform-suite:${versions.junitPlatform}",
            "org.junit.jupiter:junit-jupiter:${versions.junit}",
            "com.tngtech.archunit:archunit-junit5:${versions.archUnit}"

    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:${versions.junit}"

    compileOnly "org.projectlombok:lombok:${versions.lombok}"
    annotationProcessor "org.projectlombok:lombok:${versions.lombok}"
    testCompileOnly "org.projectlombok:lombok:${versions.lombok}"
    testAnnotationProcessor "org.projectlombok:lombok:${versions.lombok}"
}

spotless {
    encoding 'UTF-8'

    java {
        targetExclude('/target/**/*', 'build/**/*', 'node_modules/**/*')
        googleJavaFormat("${versions.googleFormat}").aosp().reflowLongStrings(true)
        licenseHeaderFile 'LICENSE', 'package '
    }

    groovyGradle {
        target '*.gradle', 'gradle/*.gradle'
    }

    format 'dotfiles', {
        target '.gitignore', '.gitattributes', '.editorconfig'
        indentWithSpaces(2)
        trimTrailingWhitespace()
        endWithNewline()
    }

    sql {
        target '**/*.sql'
        targetExclude('/target/**/*', 'build/**/*', 'node_modules/**/*')
        dbeaver()
    }

    json {
        target '**/*.json'
        targetExclude('/target/**/*', 'build/**/*', 'node_modules/**/*')
        gson()
    }
}

test {
    onlyIf { gradle.startParameter.taskNames.contains('test') }
    useJUnitPlatform()
    failFast = false
    testLogging {
        showStandardStreams = false
        events "PASSED", "FAILED", "SKIPPED"
    }
    systemProperties System.getProperties()
    systemProperty "cucumber.plugin", "io.cucumber.core.plugin.SerenityReporter"
    retry {
        maxRetries = 0
    }
    finalizedBy('aggregate')
}

tasks.withType(Test).configureEach {
    //maxParallelForks = Runtime.runtime.availableProcessors().intdiv(2) ?: 1
    maxParallelForks = Runtime.runtime.availableProcessors()
    forkEvery = 1 // This can help with managing test isolation
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.incremental = true
}

tasks.withType(Javadoc).configureEach {
    options.encoding = 'UTF-8'
}

// Tasks for checking and applying formats
tasks.named('spotlessApply') {
    group = 'formatting'
}

tasks.named('spotlessCheck') {
    group = 'verification'
}

sonar {
    properties {
        property "sonar.coverage.exclusions", "src/**/*.java"
        property "sonar.sources", "src"
        property "sonar.test.exclusions", "src/test/**/*.java"
        property "sonar.host.url", "http://127.0.0.1:9000"
        property "sonar.java.binaries", "build/classes"
        property "sonar.scm.provider", "git"
    }
}

tasks.register('npmInstall', Exec) {
    commandLine 'npm', 'install'
}

tasks.register('installLocalGitHook', Copy) {
    from new File(rootProject.rootDir, 'scripts/pre-commit')
    into { new File(rootProject.rootDir, '.git/hooks') }
    doLast {
        getProviders().exec {
            commandLine 'chmod', '775', "${destinationDir}/pre-commit"
        }
    }

    from new File(rootProject.rootDir, 'scripts/pre-push')
    into { new File(rootProject.rootDir, '.git/hooks') }
    doLast {
        getProviders().exec {
            commandLine 'chmod', '775', "${destinationDir}/pre-push"
        }
    }
}

tasks.register('archiveSerenityReports') {
    doLast {
        def reportsDir = file("target/site/serenity")
        if (reportsDir.exists()) {
            def date = new SimpleDateFormat("yyyy-MM-dd_HH-mm-ss").format(new Date())
            def archiveDir = file("target/site/history/serenity-" + date)
            reportsDir.renameTo(archiveDir)
            println "Archived previous Serenity report to: " + archiveDir
        }
    }
}

tasks.named('build') {
    dependsOn npmInstall, installLocalGitHook
}

tasks.named('sonar') {
    dependsOn spotlessApply, build
}

tasks.named('updateDaemonJvm') {
    languageVersion = JavaLanguageVersion.of(21)
}

sourceSets {
    archTest {
        java.srcDir 'src/test/java/architecture'

        // include *both* production and test code so the rule sees every Task
        compileClasspath += sourceSets.main.output  + configurations.testRuntimeClasspath
        runtimeClasspath += output + compileClasspath + sourceSets.test.output
    }
}

gradle.startParameter.continueOnFailure = false
