#!/bin/bash # Environment
set -euo pipefail # Error handling and Strict mode

set -euo pipefail # Error handling and Strict mode

function checkIfError() {
    if [ "$1" -ne 0 ] || [ "$2" -ne 0 ]; then
        return 1
    fi

    return 0
}

echo "Running pre-commit checks..."

export $(cat .env | grep SNYK) # Load Snyk token from .env file
tokenFileResult=$? # Save the exit status of the previous command

echo ""

if [[ $tokenFileResult -ne 0 ]]; then
    echo "RESULT: Pre-push checks failed. Please create the .env file with the token."
    echo ""
    exit 1
fi

# Run static analysis tools
npx snyk code test --all-projects
checkIfError $? 0 # Accumulate way to check if the previous command was successful
snykStatus=$? # Save the exit of the function

# Run dependency checks
npx snyk test --all-projects
checkIfError $snykStatus $? # Accumulate way to check if the previous command was successful
snykStatus=$? # Save the exit of the function

echo ""

if [[ $snykStatus -ne 0 ]]; then
    echo "RESULT: Pre-push checks failed. Please fix the issues before committing."
    echo ""
    exit 1
fi

echo "RESULT: Pre-push checks passed successfully."
echo ""
exit 0
