#!/bin/bash # Environment
set -euo pipefail # Error handling and Strict mode

echo "Running pre-commit checks..."

source snyk.env
tokenFileResult=$? # Save the exit status of the previous command

echo ""

if [[ $tokenFileResult -ne 0 ]]; then
    echo "RESULT: Pre-push checks failed. Please create the snyk.env file with the token."
    echo ""
    exit 1
fi

npx snyk test --all-projects
snykResult=$? # Save the exit status of the previous command

echo ""

if [[ $snykResult -ne 0 ]]; then
    echo "RESULT: Pre-push checks failed. Please fix the issues before committing."
    echo ""
    exit 1
fi

echo "RESULT: Pre-push checks passed successfully."
echo ""
exit 0
