name: Gradle Build

on:
  push:
    branches: [ "dev", "stage", "master", "main" ]
  pull_request: # Trigger on pull requests to any branch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Grant read-only access to repository contents

    steps:
      # Checkout the repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Set up JDK 11
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Node.js for Gherkin Lint
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache npm dependencies
        # The cache is only refreshed when the lock file changes,
        # leading to better cache reuse.
        uses: actions/cache@v4
        id: cache-primes
        with:
          path: |
            ~/.npm
            **/node_modules
            ~/.run
            ~/.gradle/caches
          key: dependencies-cache-${{ runner.os }}-${{ hashFiles('package-lock.json', '**/*.gradle*', 'gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
              dependencies-cache-${{ runner.os }}-
          save-always: true

      - name: Install Node.js dependencies
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build with Gradle
        run: ./gradlew build
        continue-on-error: false

      - name: Run Gherkin lint
        run: npm run lint
        continue-on-error: false

      - name: Run Spotless Lint
        run: ./gradlew spotlessCheck
        continue-on-error: false
